# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.
"""

class Pessoa:
  def __init__(self, nome, ender):
    self.set_nome(nome)
    self.set_ender(ender)

    def set_nome(self, nome):
      self,nome=nome


    def set_ender(self, ender):
      self,ender=ender

    def get_nome(self):
      return self.nome

    def get_ender(self):
      return self.ender

class Pessoa:
  def __init__(self, nome, idade):
      self.nome = nome
      self.idade = idade
  def imprimir(self):
      print(self.nome,"tem", self.idade, "anos")
  def getIdade(self):
      return self.idade
  def setIdade(self, idade):
      self.idade = idade

p = Pessoa("Ana", 25)
p.imprimir()

#HERANÇA

class Profissional(Pessoa):
  def __init__(self, nome, idade, profissao):
      super().__init__(nome, idade)
      self.profissao = profissao
  def imprimir(self):
      super().imprimir()
      print("\t e trabalha como ", self.profissao)

p = Profissional("Ana", 25, "balconista")
p.imprimir()
